### ISSUE TITLE
Undefined is not an object.

### ISSUE THREAD

**Issue by kaychess** [dappsnation/ng-rive#16]
Hello there, 
I am new to rive and angular. 
I am trying to follow the documentation provided, But having the following error [attached in screenshot].
I tried to change the rive files and tried to debug to the best of my ability. But still couldn't figure out the solution. I think the error is originating from the source files.
Can you please check the following error and help me out. 
Thank you.

<img width="824" alt="Screen Shot 2021-05-05 at 8 30 49 PM" src="https://user-images.githubusercontent.com/47786857/117225650-cdaeda00-ade0-11eb-8ddb-bd1394aeca75.png">

**Comment by GrandSchtroumpf** [comment]
This might come from a conflict of version.
Rive exports can export two type of .riv file: 
- new version: works with the lib `rive-canvas` >0.7.0
- compat version: works with `rive-canvas` >0.6.11

`ng-rive` currently only supports version 0.6.10 (compat version). Therefore, when exporting a rive file you need to use the compat version. I'll update the lib to support new version of rive this weekend I hope

**Comment by kaychess** [comment]
Thank you for your efforts @GrandSchtroumpf  🙂

**Comment by GrandSchtroumpf** [comment]
Hello, I've updated to the latest version of angular & rive-canvas. Could you give it a try and let me know how it goes ? 
```typescript
npm install ng-rive@latest
```

**Comment by kaychess** [comment]
Thanks for the update GrandSchtroumpf.  


Now updating the rive - I having following error : 

[ng] - Generating browser application bundles...
[ng] ✔ Browser application bundle generation complete.
[ng] 61 unchanged chunks
[ng] Build at: 2021-05-19T05:35:25.540Z - Hash: 7ec87648cfc502d2df72 - Time: 268ms
[ng] Error: node_modules/ng-rive/lib/animation.d.ts:39:21 - error TS2694: Namespace '"/Users/home/Developer/app/anime/main/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
[ng] 39     static ɵfac: i0.ɵɵFactoryDeclaration<RiveAnimationDirective, never>;
[ng]                        ~~~~~~~~~~~~~~~~~~~~
[ng] Error: node_modules/ng-rive/lib/animation.d.ts:40:21 - error TS2694: Namespace '"/Users/home/Developer/app/anime/main/node_modules/@angular/core/core"' has no exported member 'ɵɵDirectiveDeclaration'.
[ng] 40     static ɵdir: i0.ɵɵDirectiveDeclaration<RiveAnimationDirective, "riv-animation, [rivAnimation]", ["rivAnimation"], { "name": "name"; "index": "index"; "mix": "mix"; "speed": "speed"; "play": "play"; }, { "load": "load"; }, never>;
[ng]                        ~~~~~~~~~~~~~~~~~~~~~~
[ng] Error: node_modules/ng-rive/lib/canvas.d.ts:47:21 - error TS2694: Namespace '"/Users/home/Developer/app/anime/main/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
[ng] 47     static ɵfac: i0.ɵɵFactoryDeclaration<RiveCanvasDirective, never>;
[ng]                        ~~~~~~~~~~~~~~~~~~~~
[ng] Error: node_modules/ng-rive/lib/canvas.d.ts:48:21 - error TS2694: Namespace '"/Users/home/Developer/app/anime/main/node_modules/@angular/core/core"' has no exported member 'ɵɵDirectiveDeclaration'.
[ng] 48     static ɵdir: i0.ɵɵDirectiveDeclaration<RiveCanvasDirective, "canvas[riv]", ["rivCanvas"], { "riv": "riv"; "name": "artboard"; "viewbox": "viewbox"; "lazy": "lazy"; "fit": "fit"; "alignment": "alignment"; "height": "height"; }, { "artboardChange": "artboardChange"; }, never>;
[ng]                        ~~~~~~~~~~~~~~~~~~~~~~
[ng] Error: node_modules/ng-rive/lib/component/bone.d.ts:10:21 - error TS2694: Namespace '"/Users/home/Developer/app/anime/main/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
[ng] 10     static ɵfac: i0.ɵɵFactoryDeclaration<RiveBone, never>;
[ng]                        ~~~~~~~~~~~~~~~~~~~~
[ng] Error: node_modules/ng-rive/lib/component/bone.d.ts:11:21 - error TS2694: Namespace '"/Users/home/Developer/app/anime/main/node_modules/@angular/core/core"' has no exported member 'ɵɵDirectiveDeclaration'.
[ng] 11     static ɵdir: i0.ɵɵDirectiveDeclaration<RiveBone, "riv-bone, [rivBone]", ["rivBone"], { "length": "length"; }, {}, never>;
[ng]                        ~~~~~~~~~~~~~~~~~~~~~~
[ng] Error: node_modules/ng-rive/lib/component/node.d.ts:13:21 - error TS2694: Namespace '"/Users/home/Developer/app/anime/main/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
[ng] 13     static ɵfac: i0.ɵɵFactoryDeclaration<RiveNode, never>;
[ng]                        ~~~~~~~~~~~~~~~~~~~~
[ng] Error: node_modules/ng-rive/lib/component/node.d.ts:14:21 - error TS2694: Namespace '"/Users/home/Developer/app/anime/main/node_modules/@angular/core/core"' has no exported member 'ɵɵDirectiveDeclaration'.
[ng] 14     static ɵdir: i0.ɵɵDirectiveDeclaration<RiveNode, "riv-node, [rivNode]", ["rivNode"], { "x": "x"; "y": "y"; }, {}, never>;
[ng]                        ~~~~~~~~~~~~~~~~~~~~~~
[ng] Error: node_modules/ng-rive/lib/component/root-bone.d.ts:12:21 - error TS2694: Namespace '"/Users/home/Developer/app/anime/main/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
[ng] 12     static ɵfac: i0.ɵɵFactoryDeclaration<RiveRootBone, never>;
[ng]                        ~~~~~~~~~~~~~~~~~~~~
[ng] Error: node_modules/ng-rive/lib/component/root-bone.d.ts:13:21 - error TS2694: Namespace '"/Users/home/Developer/app/anime/main/node_modules/@angular/core/core"' has no exported member 'ɵɵDirectiveDeclaration'.
[ng] 13     static ɵdir: i0.ɵɵDirectiveDeclaration<RiveRootBone, "riv-root-bone, [rivRootBone]", ["rivRootBone"], { "x": "x"; "y": "y"; "length": "length"; }, {}, never>;
[ng]                        ~~~~~~~~~~~~~~~~~~~~~~
[ng] Error: node_modules/ng-rive/lib/component/transform-component.d.ts:18:21 - error TS2694: Namespace '"/Users/home/Developer/app/anime/main/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
[ng] 18     static ɵfac: i0.ɵɵFactoryDeclaration<RiveTransformComponent<any>, never>;
[ng]                        ~~~~~~~~~~~~~~~~~~~~
[ng] Error: node_modules/ng-rive/lib/component/transform-component.d.ts:19:21 - error TS2694: Namespace '"/Users/home/Developer/app/anime/main/node_modules/@angular/core/core"' has no exported member 'ɵɵDirectiveDeclaration'.
[ng] 19     static ɵdir: i0.ɵɵDirectiveDeclaration<RiveTransformComponent<any>, never, never, { "name": "name"; "scale": "scale"; "scaleX": "scaleX"; "scaleY": "scaleY"; "rotation": "rotation"; }, {}, never>;
[ng]                        ~~~~~~~~~~~~~~~~~~~~~~
[ng] Error: node_modules/ng-rive/lib/module.d.ts:11:21 - error TS2694: Namespace '"/Users/home/Developer/app/anime/main/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
[ng] 11     static ɵfac: i0.ɵɵFactoryDeclaration<RiveModule, never>;
[ng]                        ~~~~~~~~~~~~~~~~~~~~
[ng] Error: node_modules/ng-rive/lib/module.d.ts:12:21 - error TS2694: Namespace '"/Users/home/Developer/app/anime/main/node_modules/@angular/core/core"' has no exported member 'ɵɵNgModuleDeclaration'.
[ng] 12     static ɵmod: i0.ɵɵNgModuleDeclaration<RiveModule, [typeof i1.RiveCanvasDirective, typeof i2.RiveAnimationDirective, typeof i3.RivePlayer, typeof i4.RiveNode, typeof i5.RiveBone, typeof i6.RiveRootBone, typeof i7.RiveSMInput, typeof i7.RiveStateMachine], [typeof i8.HttpClientModule], [typeof i1.RiveCanvasDirective, typeof i2.RiveAnimationDirective, typeof i3.RivePlayer, typeof i4.RiveNode, typeof i5.RiveBone, typeof i6.RiveRootBone, typeof i7.RiveSMInput, typeof i7.RiveStateMachine]>;
[ng]                        ~~~~~~~~~~~~~~~~~~~~~
[ng] Error: node_modules/ng-rive/lib/module.d.ts:13:21 - error TS2694: Namespace '"/Users/home/Developer/app/anime/main/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'.
[ng] 13     static ɵinj: i0.ɵɵInjectorDeclaration<RiveModule>;
[ng]                        ~~~~~~~~~~~~~~~~~~~~~
[ng] Error: node_modules/ng-rive/lib/player.d.ts:56:21 - error TS2694: Namespace '"/Users/home/Developer/app/anime/main/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
[ng] 56     static ɵfac: i0.ɵɵFactoryDeclaration<RivePlayer, never>;
[ng]                        ~~~~~~~~~~~~~~~~~~~~
[ng] Error: node_modules/ng-rive/lib/player.d.ts:57:21 - error TS2694: Namespace '"/Users/home/Developer/app/anime/main/node_modules/@angular/core/core"' has no exported member 'ɵɵDirectiveDeclaration'.
[ng] 57     static ɵdir: i0.ɵɵDirectiveDeclaration<RivePlayer, "riv-player, [rivPlayer]", ["rivPlayer"], { "name": "name"; "index": "index"; "mix": "mix"; "mode": "mode"; "speed": "speed"; "play": "play"; "autoreset": "autoreset"; "time": "time"; }, { "timeChange": "timeChange"; "playChange": "playChange"; "speedChange": "speedChange"; "load": "load"; }, never>;
[ng]                        ~~~~~~~~~~~~~~~~~~~~~~
[ng] Error: node_modules/ng-rive/lib/service.d.ts:17:21 - error TS2694: Namespace '"/Users/home/Developer/app/anime/main/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
[ng] 17     static ɵfac: i0.ɵɵFactoryDeclaration<RiveService, [{ optional: true; }, { optional: true; }, null]>;
[ng]                        ~~~~~~~~~~~~~~~~~~~~
[ng] Error: node_modules/ng-rive/lib/service.d.ts:18:22 - error TS2694: Namespace '"/Users/home/Developer/app/anime/main/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectableDeclaration'.
[ng] 18     static ɵprov: i0.ɵɵInjectableDeclaration<RiveService>;
[ng]                         ~~~~~~~~~~~~~~~~~~~~~~~
[ng] Error: node_modules/ng-rive/lib/state-machine.d.ts:23:21 - error TS2694: Namespace '"/Users/home/Developer/app/anime/main/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
[ng] 23     static ɵfac: i0.ɵɵFactoryDeclaration<RiveSMInput, never>;
[ng]                        ~~~~~~~~~~~~~~~~~~~~
[ng] Error: node_modules/ng-rive/lib/state-machine.d.ts:24:21 - error TS2694: Namespace '"/Users/home/Developer/app/anime/main/node_modules/@angular/core/core"' has no exported member 'ɵɵDirectiveDeclaration'.
[ng] 24     static ɵdir: i0.ɵɵDirectiveDeclaration<RiveSMInput, "riv-input, [rivInput]", ["rivInput"], { "name": "name"; "value": "value"; }, { "change": "change"; "load": "load"; }, never>;
[ng]                        ~~~~~~~~~~~~~~~~~~~~~~
[ng] Error: node_modules/ng-rive/lib/state-machine.d.ts:57:21 - error TS2694: Namespace '"/Users/home/Developer/app/anime/main/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
[ng] 57     static ɵfac: i0.ɵɵFactoryDeclaration<RiveStateMachine, never>;
[ng]                        ~~~~~~~~~~~~~~~~~~~~
[ng] Error: node_modules/ng-rive/lib/state-machine.d.ts:58:21 - error TS2694: Namespace '"/Users/home/Developer/app/anime/main/node_modules/@angular/core/core"' has no exported member 'ɵɵDirectiveDeclaration'.
[ng] 58     static ɵdir: i0.ɵɵDirectiveDeclaration<RiveStateMachine, "riv-state-machine, [rivStateMachine]", ["rivStateMachine"], { "name": "name"; "index": "index"; "speed": "speed"; "play": "play"; }, { "load": "load"; }, ["riveInputs"]>;
[ng]                        ~~~~~~~~~~~~~~~~~~~~~~
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 96:10-28
[ng] "export 'ɵɵFactoryTarget' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 330:10-28
[ng] "export 'ɵɵFactoryTarget' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 676:10-28
[ng] "export 'ɵɵFactoryTarget' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 920:10-28
[ng] "export 'ɵɵFactoryTarget' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 1043:10-28
[ng] "export 'ɵɵFactoryTarget' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 1132:10-28
[ng] "export 'ɵɵFactoryTarget' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 1200:10-28
[ng] "export 'ɵɵFactoryTarget' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 1272:10-28
[ng] "export 'ɵɵFactoryTarget' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 1411:10-28
[ng] "export 'ɵɵFactoryTarget' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 1616:10-28
[ng] "export 'ɵɵFactoryTarget' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 1695:10-28
[ng] "export 'ɵɵFactoryTarget' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 104:0-27
[ng] "export 'ɵɵngDeclareClassMetadata' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 349:0-27
[ng] "export 'ɵɵngDeclareClassMetadata' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 699:0-27
[ng] "export 'ɵɵngDeclareClassMetadata' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 937:0-27
[ng] "export 'ɵɵngDeclareClassMetadata' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 1055:0-27
[ng] "export 'ɵɵngDeclareClassMetadata' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 1144:0-27
[ng] "export 'ɵɵngDeclareClassMetadata' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 1211:0-27
[ng] "export 'ɵɵngDeclareClassMetadata' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 1285:0-27
[ng] "export 'ɵɵngDeclareClassMetadata' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 1426:0-27
[ng] "export 'ɵɵngDeclareClassMetadata' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 1643:0-27
[ng] "export 'ɵɵngDeclareClassMetadata' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 1714:0-27
[ng] "export 'ɵɵngDeclareClassMetadata' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 82:19-40
[ng] "export 'ɵɵngDeclareFactory' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 318:27-48
[ng] "export 'ɵɵngDeclareFactory' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 664:18-39
[ng] "export 'ɵɵngDeclareFactory' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 908:30-51
[ng] "export 'ɵɵngDeclareFactory' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 1033:30-51
[ng] "export 'ɵɵngDeclareFactory' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 1122:16-37
[ng] "export 'ɵɵngDeclareFactory' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 1190:16-37
[ng] "export 'ɵɵngDeclareFactory' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 1262:20-41
[ng] "export 'ɵɵngDeclareFactory' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 1403:19-40
[ng] "export 'ɵɵngDeclareFactory' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 1604:24-45
[ng] "export 'ɵɵngDeclareFactory' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 1689:18-39
[ng] "export 'ɵɵngDeclareFactory' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 98:20-44
[ng] "export 'ɵɵngDeclareInjectable' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 1706:18-40
[ng] "export 'ɵɵngDeclareInjector' (imported as 'i0') was not found in '@angular/core'
[ng] Error: ./node_modules/ng-rive/fesm2015/ng-rive.js 1697:18-40
[ng] "export 'ɵɵngDeclareNgModule' (imported as 'i0') was not found in '@angular/core'

**Comment by GrandSchtroumpf** [comment]
The latest version of ng-rive is compatible with angular 12 only. As this is a very new library and angular 12 is the latest version I would rather not spend time on retro compatibility for versions of ng-rive above 0.1.0.
If retro compatibility is a must for you, please let me know and I'll do my best to debug and make is work with previous version of angular.

**Comment by kaychess** [comment]
No worries. I updated angular
